name: Code quality

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  code-quality:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - name: "checking out"
      uses: actions/checkout@v2

    - name: Setup Node and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ./node\_modules
        key: ${{ runner.OS }}-dependencies-${{ hashFiles('\*\*/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-dependencies-${{ env.cache-name }}-
          ${{ runner.OS }}-dependencies-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: |
        npm install

    - name: Lint files
      run: |
        npm test